### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [Raku/docker#10]
I was use this image build on arm64 and successed , So I think it can be support arm64 and we can add it to https://hub.docker.com/u/arm64v8/ .
See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images.

**Comment by hoelzro** [comment]
Note to self: look at https://github.com/docker-library/official-images/blob/master/library/php and apply to https://github.com/docker-library/official-images/blob/master/library/rakudo-star

**Comment by zakame** [comment]
@hoelzro I can help out as well (I help maintain https://github.com/Perl/docker-perl.)  This is probably as minimal as https://github.com/docker-library/official-images/blob/master/library/perl

**Comment by longquan7** [comment]
I have no permission to modify the file of https://github.com/docker-library/official-images/blob/master/library/rakudo-star

**Comment by hoelzro** [comment]
@zakame That would be great!

@longquan7 You need to create your own fork, work in that, and then submit a PR.  If you do that, you can tag me and I'll help review the change.

**Comment by longquan7** [comment]
@zakame OK,thanks

**Comment by JJ** [comment]
@zakame do you mean that there's no change we need to do in this repository, but just to change that description in the "official" docker repos file? Will it build automatically for the architectures we tag?

**Comment by zakame** [comment]
@JJ yep, likely just add `arm32v7, arm64v8` in the `Architectures` header.

**Comment by nxadm** [comment]
Just a reminder that JIT only works on amd64. Depending on the case this will result in a slower Rakudo in other platforms (including i386).

**Comment by hoelzro** [comment]
Ok, this has been added to the rakudo-star docker image!
