### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ufobat** [Raku/docker#14]
Could you please update to the current rakudo star release?

**Comment by JJ** [comment]
Sure!

**Comment by JJ** [comment]
We need someone to communicate it to Docker via modification of the file mentioned in #10. I can do it if @hoelzro can't.

**Comment by hoelzro** [comment]
I can take care of this today!

**Comment by hoelzro** [comment]
Done! https://github.com/docker-library/official-images/pull/3955
