### ISSUE TITLE
Outdated info on hub.docker.com

### ISSUE THREAD

**Issue by zoffixznet** [Raku/docker#15]
I don't know anything about docker, but I guess we're responsible for this page? https://hub.docker.com/_/rakudo-star/

This paragraph sounds a tad outdated:

> Rakudo Star is a Perl 6 distribution designed for use by early adopters of the language. It includes a virtual machine (the JVM or MoarVM), the Rakudo Perl 6 compiler, and a suite of modules that users may find useful. This image includes the MoarVM backend for the compiler.

If I had to reword it, I'd write it as:

> Rakudo Star is a Perl 6 compiler distribution that includes MoarVM virtual machine, Rakudo Perl 6 compiler, a suite of modules that users may find useful, and language documentation.

Also, the "Contributing/Getting Help" section lists RT as the bug tracker. Since RT's interface is disabled and it's falling out of favour of the core devs, it's probably better to include our GitHub-based tracker instead: https://github.com/rakudo/rakudo/issues/new

**Comment by hoelzro** [comment]
@zoffixznet Yes - it's composed from the contents of README.md and README-short.txt

**Comment by zoffixznet** [comment]
Thanks!

**Comment by Tekki** [comment]
Now we have 2018.10 on Docker, but the readme is still the same old version. For example we still see the wrong example `docker run -it rakudo-star -e 'say "Hello!"'` instead of `docker run -it rakudo-star perl6 -e 'say "Hello!"'`.
