### ISSUE TITLE
Update latest official Image to 2018.04

### ISSUE THREAD

**Issue by skaji** [Raku/docker#16]
Could @hoelzro  or someone update latest official Image to 2018.04?
cf https://github.com/perl6/docker/issues/14#issuecomment-361771304

**Comment by hoelzro** [comment]
Thanks @skaji! I didn't even realize there had been a release!

@jstuder-gh If you update the Dockerfile in the future, could you ping me so I can submit the change to the Docker library?  Alternatively, I could walk you through the process if you want to do it yourself!

**Comment by hoelzro** [comment]
PR made: https://github.com/docker-library/official-images/pull/4352

**Comment by jstuder-gh** [comment]
@hoelzro, sorry about that! I will be sure to ping you in the future.

**Comment by skaji** [comment]
https://github.com/docker-library/official-images/pull/4352 were merged.
@hoelzro thanks!

**Comment by jstuder-gh** [comment]
@hoelzro, for 2018.06, I updated this Dockerfile and submitted a PR to docker-library ([here](https://github.com/docker-library/official-images/pull/4696)). Is there anything else that needs to be done in order to update the official image? Thanks.

**Comment by hoelzro** [comment]
@jstuder-gh Yeah, looks good to me!
