### ISSUE TITLE
`docker build <this project>` SEGFAULTS

### ISSUE THREAD

**Issue by lag-linaro** [Raku/docker#17]
Please see the following build log when I attempt to `docker build` this project.

https://gist.github.com/lag-linaro/c45071d954c213868107c8dc487ae0a6

Any idea what's happening?

**Comment by hoelzro** [comment]
Hi @lag-linaro - out of curiosity, how much memory does your build machine have?

**Comment by lag-linaro** [comment]
Around 256GB give or take a Byte or 2.

Why?  What are you thinking?

**Comment by hoelzro** [comment]
Ah, ok - so OOM is probably not the issue!

**Comment by hoelzro** [comment]
Ok, I tried building this on my machine and it worked ok - could you try again (you might want to delete all intermediary layers from your previous build to be on the safe side)?  If it still fails, what environment (OS version, Docker version, etc) are you running?

**Comment by hoelzro** [comment]
@lag-linaro Also, if you just want to use the image, it's part of the official Docker repository, so you can run it via `docker run -it rakudo-star`.

**Comment by lag-linaro** [comment]
@hoelzro thanks for getting back to me.

`docker run` and `docker pull` won't work for me since I am building on ARM64v8.

I don't see any reason why `docker build` shouldn't work on this architecture.

Is there anything I can do to debug why it's segfaulting?

**Comment by JJ** [comment]
It is segfaulting when building Rakudo, in a step in which it's running MoarVM for the first time. I assume you don't have the same problem when building Perl 6 standalone. If that's the case, it might be a matter of versions of the compiler or tools used to build. If it segfaults also when doing it outside Docker, it might be better if you file an issue with moar, since that seems to be the problem.

**Comment by hoelzro** [comment]
@JJ Good suggestion! @lag-linaro Could you try that?

**Comment by lag-linaro** [comment]
Could well be a tooling issue.  This appears to be working in [Docker's Official Images Builder](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/perl/).

Closing this for now.  Will re-visit if we experience any more issues.
