### ISSUE TITLE
en_US.UTF8 locale support please

### ISSUE THREAD

**Issue by librasteve** [Raku/docker#22]
Hi - I am keen to use perl6/docker for development, not just run a script or repl. But.... perl6/raku really could use unicode support such as en_US.UTF8. I have tried appending variants like this in the Dockerfile, but do not have the skills to get it working ;-(. ...
```
ENV LANG=en_US.UTF-8  
RUN apt-get clean \
    && apt-get --yes update \
    && apt-get --yes install locales \
    && echo "LANG=en_US.UTF-8" >> /etc/environment \
    && locale-gen \
    && dpkg-reconfigure locales 
```

**Comment by tianon** [comment]
Try "C.UTF-8" (it should be included out of the box).

**Comment by librasteve** [comment]
Yep - you got it! tx...
