### ISSUE TITLE
Push new 2020.10 image to docker hub

### ISSUE THREAD

**Issue by m-dango** [Raku/docker#37]
The current 2010.10 image on docker hub is missing `/usr/share/perl6/vendor/bin/` from `$PATH`, which contains `zef`, `prove6` etc. This issue was fixed in https://github.com/Raku/docker/pull/36. A new image should be pushed to docker hub so that these commands can be run normally.

**Comment by JJ** [comment]
Let me see if I can handle that. Thanks for the report.

**Comment by JJ** [comment]
Wait, what current image you mean? I just created a "Rakulang" group in Docker Hub to take care of this. I'm not really sure who's in charge of that image. Is it the Rakudo image?

**Comment by JJ** [comment]
I have created [this organization](https://hub.docker.com/orgs/rakulang), let me know your Docker Hub user so that I can add you. Also, you can maybe figure out how to create a repo without linking it to my personal account... I have found no way to link it to this organization. Maybe via webhooks.

**Comment by JJ** [comment]
Nope, no way to link the organization, despite it being theoretically possible...

**Comment by JJ** [comment]
OTOH, it's entirely possible that I don't have the privileges to do so.

**Comment by JJ** [comment]
Closing ~because I have fat fingers~because I don't really see a way for me to fix it. Maybe someone else can reopen and try and fix it.

**Comment by m-dango** [comment]
It looks like it needs to be changed in the https://github.com/docker-library/official-images repo. I've created PR https://github.com/docker-library/official-images/pull/9100 for this update.

**Comment by JJ** [comment]
Thanks!
