### ISSUE TITLE
Request 2021.02.1 rakudo-star Docker official images

### ISSUE THREAD

**Issue by japhb** [Raku/docker#43]
Noticed in RWN that the new Rakudo Star is out, but https://hub.docker.com/_/rakudo-star has not been updated yet.  I'm not sure who to ask, but this is listed as the "Where to file issues" link, so I figured I'd start there.

(FWIW, I'm asking because there are actually fixes in 2021.02.1 and current zef/fez that I want to include in Docker images that *I* am making, not just for the fun of the bump.  :grin:)

**Comment by JJ** [comment]
Will do. Thanks for reporting it.

**Comment by jmaslak** [comment]
This is related to #46

**Comment by jmaslak** [comment]
I've created https://github.com/docker-library/official-images/pull/10300 to update Docker official image to 2021.04.

**Comment by jmaslak** [comment]
2021.04 is now available via Docker Hub, both as :latest and :2021.04.

I'm going to assume this will solve your issue, so I'm going to close the issue, but if this doesn't solve the issue, feel free to re-open.

**Comment by japhb** [comment]
Yup, solved, thank you!  :-)
