### ISSUE TITLE
Wrong Dockerfile in docker-library

### ISSUE THREAD

**Issue by m-dango** [Raku/docker#7]
`docker pull` still gets you 2016.11 as latest from the official repo:
https://github.com/docker-library/official-images/blob/master/library/rakudo-star

**Comment by hoelzro** [comment]
There's an outstanding pr to update the docker library with 2017.0: https://github.com/docker-library/official-images/pull/2599

**Comment by m-dango** [comment]
Ah I see. Maybe master or a tag could have a Dockerfile with `rakudo_version=latest`, with other branches/tags pointing to specific releases? (EDIT: This goes against their expectation of repeatability i.e "rebuilding the same Dockerfile should result in the same version of the image being packaged." Ignore me, I'm no Docker expert 🙂)

**Comment by JJ** [comment]
Will try to take a look. Meanwhile, there are also unofficial images
updated to 2017.01 https://hub.docker.com/r/jjmerelo/alpine-perl6/

**Comment by m-dango** [comment]
I think we'll either need to give them a well defined use case for https://github.com/perl6/docker/pull/6 or take it out, as we seem to be at a bit of an impasse with it.

**Comment by hoelzro** [comment]
Does anyone mind if I roll back #6 for now, just to get the new image built?

**Comment by hoelzro** [comment]
↑ @JJ

**Comment by tianon** [comment]
I think the markdown changes there are fine -- I was planning to comment
later today recommending to roll back the Dockerfile change but you beat me
to the punch. 😇

**Comment by hoelzro** [comment]
In the interest of getting the new image out there, I'm going to revert #6.  We can always bring it back if needed.
